In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import librosa    
import os

In [2]:
###### Open train and test file
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
train.head()

   ID         Class
0   0         siren
1   1  street_music
2   2      drilling
3   3         siren
4   4      dog_bark

In [4]:
train["Class"].unique()

array(['siren', 'street_music', 'drilling', 'dog_bark',
       'children_playing', 'gun_shot', 'engine_idling', 'air_conditioner',
       'jackhammer', 'car_horn'], dtype=object)

In [5]:
bitrate = 16384
columns = []

for x in range(bitrate//2):
    columns.append(x)
    train[x] = 0
    test[x] = 0

In [6]:
os.chdir("Train/")

In [10]:
i = 0

rows_list = []

for filename in os.listdir():   
    print(filename)
    i += 1
    file, rate = librosa.load(filename, sr=bitrate)
    test = np.fft.fft(file, norm="ortho")
    
    #### Normalize fft
    result = abs(test[:rate//2])
    result = result - result.mean()
    result = result / result.max()

    #plt.plot(file)
    #plt.show()
    #plt.plot(result)
    #plt.show()
    
    name, _ = filename.split(".")
    row_list = []
    row_list.append(dict(result) for a in columns))
    dict1 = dict( (a,np.random.randint(100)) for a in ['A','B','C','D','E'])
    row_list.append(dict1)

df4 = pd.DataFrame(row_list, columns=['A','B','C','D','E'])
    train.loc[train['ID'] == name, columns] = result
    
    if i == 5:
        break

0.wav

KeyboardInterrupt:

In [27]:
row_list = []
row_list.append(dict((name, result[a]) for a in columns))
dict1 = dict((name, result[a]) for a in columns)
row_list.append(dict1)
df4 = pd.DataFrame(row_list, columns=columns)
df4

,0,1,2,3,4,5,6,7,8,9,...,8182,8183,8184,8185,8186,8187,8188,8189,8190,8191
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
train.head()

,ID,Class,0,1,2,3,4,5,6,7,...,8182,8183,8184,8185,8186,8187,8188,8189,8190,8191
0,0,siren,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,1,street_music,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,2,drilling,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,3,siren,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,4,dog_bark,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0